name: Run TGForwarder

on:
  schedule:
    # 每天 UTC 时间 8:00 运行（北京时间 16:00）
  - cron: "0 */8 * * *"
  # 也可以手动触发
  workflow_dispatch:
  
jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行脚本
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
        run: |
          # 替换脚本中的敏感字段
          sed -i "s/api_id = .*/api_id = $API_ID/" TGForwarder.py
          sed -i "s/api_hash = .*/api_hash = '$API_HASH'/" TGForwarder.py
          sed -i "s/string_session = .*/string_session = '$STRING_SESSION'/" TGForwarder.py
          # 执行脚本
          python TGForwarder.py
